name: main

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Print a Bitcoin chart
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Ping for review
        uses: blombard/review-reminder@master
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          reminder-comment: "Don't forget to review this PR !"
          days-before-reminder: '0'
      - name: Save the new Bitcoin chart
        uses: ./ # Uses an action in the root directory
        id: chart
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Bitcoin chart

          commit_user_name: actions-user
          commit_user_email: actions@github.com
          commit_author: Author <actions@github.com>
